name = "khofly"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-04-26"
compatibility_flags = ["nodejs_compat"]

[vars]
PNPM_VERSION = "8.7.1"
HOST = "http://localhost:3000"
SEARXNG_URL_EU1 = "https://searxng-eu1.khofly.com"
SEARXNG_URL_US1 = "https://searxng-us1.khofly.com"
NOMINATIM_URL = "https://nominatim.openstreetmap.org"
ANALYZE = 0
IS_SELF_HOST = 0
APP_NAME = "Khofly"
HOST_TARGET = "cloudflare"
SEARXNG_URL_SELF_HOST = "https://searxng-eu1.khofly.com"