const subdomainsToRemove = [
  "www", // Everything
  "aa",
  "ab",
  "abs",
  "ace",
  "ady",
  "af",
  "ak",
  "als",
  "alt",
  "am",
  "an",
  "ang",
  "anp",
  "ar",
  "arc",
  "arn",
  "arq",
  "ary",
  "arz",
  "as",
  "ast",
  "atj",
  "av",
  "avk",
  "awa",
  "ay",
  "az",
  "azb",
  "ba",
  "ban",
  "bar",
  "bat-smg",
  "bcl",
  "be",
  "be-tarask",
  "bg",
  "bgn",
  "bh",
  "bi",
  "bjn",
  "bm",
  "bn",
  "bo",
  "bpy",
  "br",
  "bs",
  "btm",
  "bug",
  "bxr",
  "ca",
  "cdo",
  "ce",
  "ceb",
  "ch",
  "cho",
  "chr",
  "chy",
  "ckb",
  "co",
  "cr",
  "crh",
  "cs",
  "csb",
  "cu",
  "cv",
  "cy",
  "da",
  "de",
  "din",
  "diq",
  "dsb",
  "dty",
  "dv",
  "dz",
  "ee",
  "egl",
  "el",
  "eml",
  "en",
  "eo",
  "es",
  "et",
  "eu",
  "ext",
  "fa",
  "ff",
  "fi",
  "fiu-vro",
  "fj",
  "fo",
  "fr",
  "frp",
  "frr",
  "fur",
  "fy",
  "ga",
  "gag",
  "gan",
  "gcr",
  "gd",
  "gl",
  "glk",
  "gn",
  "gom",
  "gor",
  "got",
  "gpe",
  "gu",
  "gur",
  "gv",
  "ha",
  "hak",
  "haw",
  "he",
  "hi",
  "hif",
  "ho",
  "hr",
  "hsb",
  "ht",
  "hu",
  "hy",
  "hyw",
  "hz",
  "ia",
  "id",
  "ie",
  "ig",
  "ii",
  "ik",
  "ilo",
  "inh",
  "io",
  "is",
  "it",
  "iu",
  "ja",
  "jbo",
  "jv",
  "ka",
  "kaa",
  "kab",
  "kbd",
  "kbp",
  "kcg",
  "kg",
  "ki",
  "kj",
  "kk",
  "kl",
  "km",
  "kn",
  "ko",
  "koi",
  "krc",
  "kri",
  "krj",
  "ks",
  "ksh",
  "ku",
  "kv",
  "kw",
  "ky",
  "la",
  "lad",
  "lb",
  "lbe",
  "lez",
  "lfn",
  "lg",
  "li",
  "lij",
  "lki",
  "lld",
  "lmo",
  "ln",
  "lo",
  "lrc",
  "lt",
  "ltg",
  "lus",
  "luz",
  "lv",
  "mad",
  "mai",
  "map-bms",
  "mdf",
  "mg",
  "mh",
  "mhr",
  "mi",
  "min",
  "mk",
  "ml",
  "mn",
  "mni",
  "mnw",
  "mo",
  "mr",
  "mrj",
  "ms",
  "mt",
  "mus",
  "mwl",
  "my",
  "myv",
  "mzn",
  "na",
  "nah",
  "nan",
  "nap",
  "nds",
  "nds-nl",
  "ne",
  "new",
  "ng",
  "nia",
  "niu",
  "nl",
  "nn",
  "no",
  "nod",
  "nov",
  "nqo",
  "nrm",
  "nso",
  "nv",
  "ny",
  "oc",
  "olo",
  "om",
  "or",
  "os",
  "pa",
  "pag",
  "pam",
  "pap",
  "pcd",
  "pdc",
  "pfl",
  "pi",
  "pih",
  "pl",
  "pms",
  "pnb",
  "pnt",
  "prg",
  "ps",
  "pt",
  "pu",
  "qu",
  "rgn",
  "rm",
  "rmy",
  "rn",
  "ro",
  "roa-rup",
  "roa-tara",
  "ru",
  "rue",
  "rw",
  "sa",
  "sah",
  "sat",
  "sc",
  "scn",
  "sco",
  "sd",
  "se",
  "sei",
  "sg",
  "sh",
  "shi",
  "shn",
  "shy",
  "si",
  "simple",
  "sk",
  "skr",
  "sl",
  "sm",
  "smn",
  "sn",
  "so",
  "sq",
  "sr",
  "srn",
  "ss",
  "st",
  "stq",
  "su",
  "sv",
  "sw",
  "szl",
  "szy",
  "ta",
  "tay",
  "tcy",
  "te",
  "tet",
  "tg",
  "th",
  "ti",
  "tk",
  "tl",
  "tn",
  "to",
  "tpi",
  "tr",
  "tru",
  "ts",
  "tt",
  "tum",
  "tw",
  "ty",
  "tyv",
  "tzm",
  "udm",
  "ug",
  "uk",
  "ur",
  "uz",
  "ve",
  "vec",
  "vep",
  "vi",
  "vls",
  "vo",
  "vot",
  "vro",
  "wa",
  "war",
  "wo",
  "wuu",
  "xal",
  "xh",
  "xmf",
  "yi",
  "yo",
  "yue",
  "za",
  "zea",
  "zgh",
  "zh",
  "zh-classical",
  "zh-min-nan",
  "zh-yue",
  "zu",
];
// Doesn't remove all subdomains, just www and lang codes
export const removeSubdomain = (domain: string) => {
  // Remove protocol (http://, https://)
  const cleanedDomain = domain.replace(/^(https?:\/\/)?/, "");

  // Split the domain into parts
  const parts = cleanedDomain.split(".");
  const subdomain = parts[0];

  // Check if there are subdomains to remove
  if (subdomainsToRemove.includes(subdomain)) {
    // Return everything but the subdomain
    return parts.slice(1).join(".");
  } else {
    // Return everything
    return cleanedDomain;
  }
};

export const popularDomainNameMap: { [key: string]: string } = {
  // Google stuff
  "google.com": "Google",
  "mail.google.com": "Gmail",
  "maps.google.com": "Google Maps",
  "drive.google.com": "Google Drive",
  "calendar.google.com": "Google Calendar",
  "photos.google.com": "Google Photos",
  "news.google.com": "Google News",
  "play.google.com": "Google Play Store",
  "accounts.google.com": "Google Accounts",
  "developers.google.com": "Google Developers",
  "cloud.google.com": "Google Cloud",
  "gemini.google.com": "Gemini",
  "youtube.com": "YouTube",

  // Proton stuff
  "proton.me": "Proton",
  "account.proton.me": "Proton Account",
  "pass.proton.me": "Proton Pass",
  "drive.proton.me": "Proton Drive",
  "mail.proton.me": "Proton Mail",
  "calendar.proton.me": "Proton Calendar",
  "wallet.proton.me": "Proton Wallet",
  "protonvpn.com": "Proton VPN",
  "account.protonvpn.com": "Proton Account",

  // Browser stuff
  "mozilla.org": "Mozilla",
  "brave.com": "Brave",
  "opera.com": "Opera",
  "floorp.app": "Floorp",
  "zen-browser.app": "Zen Browser",
  "docs.zen-browser.app": "Zen Browser",
  "vivaldi.com": "Vivaldi",
  "vivaldi.net": "Vivaldi",
  "forum.vivaldi.net": "Vivaldi Forum",
  "bing.com": "Bing",
  "duckduckgo.com": "DuckDuckGo",
  "yandex.com": "Yandex",
  "startpage.com": "Startpage",
  "qwant.com": "Qwant",
  "searx.me": "SearX",
  "searxng.org": "SearXNG",
  "khofly.com": "Khofly",
  "staging.khofly.com": "Khofly",

  "flathub.org": "Flathub",
  "facebook.com": "Facebook",
  "twitter.com": "X (formerly Twitter)",
  "instagram.com": "Instagram",
  "amazon.com": "Amazon",
  "wikipedia.org": "Wikipedia",
  "reddit.com": "Reddit",
  "linkedin.com": "LinkedIn",
  "github.com": "GitHub",
  "netflix.com": "Netflix",
  "yahoo.com": "Yahoo",
  "microsoft.com": "Microsoft",
  "apple.com": "Apple",
  "nytimes.com": "The New York Times",
  "bbc.com": "BBC",
  "espn.com": "ESPN",
  "cnn.com": "CNN",
  "walmart.com": "Walmart",
  "ebay.com": "eBay",
  "craigslist.org": "Craigslist",
  "pinterest.com": "Pinterest",
  "tiktok.com": "TikTok",
  "twitch.tv": "Twitch",
  "discord.com": "Discord",
  "spotify.com": "Spotify",
  "paypal.com": "PayPal",
  "adobe.com": "Adobe",
  "salesforce.com": "Salesforce",
  "wordpress.com": "WordPress.com",
  "medium.com": "Medium",
  "vimeo.com": "Vimeo",
  "dropbox.com": "Dropbox",
  "slack.com": "Slack",
  "zoom.us": "Zoom",
  "canva.com": "Canva",
  "quora.com": "Quora",
  "indeed.com": "Indeed",
  "booking.com": "Booking.com",
  "tripadvisor.com": "Tripadvisor",
  "reuters.com": "Reuters",
  "bloomberg.com": "Bloomberg",
  "wsj.com": "The Wall Street Journal",
  "huffpost.com": "HuffPost",
  "msn.com": "MSN",
  "weather.com": "The Weather Channel",
  "irs.gov": "IRS",
  "cdc.gov": "CDC",
  "nih.gov": "NIH",
  "fandom.com": "Fandom",
  "etsy.com": "Etsy",
  "soundcloud.com": "SoundCloud",
  "telegram.org": "Telegram",
  "gitlab.com": "GitLab",
  "stackexchange.com": "Stack Exchange",
  "steampowered.com": "Steam",
  "roblox.com": "Roblox",
  "epicgames.com": "Epic Games",
  "alibaba.com": "Alibaba",
  "jd.com": "JD.com",
  "naver.com": "Naver",
  "daum.net": "Daum",
  "qq.com": "QQ",
  "weibo.com": "Weibo",
  "yandex.ru": "Yandex",
  "ok.ru": "OK.ru",
  "vk.com": "VK",
  "live.com": "Microsoft Live",
  "office.com": "Microsoft Office",
  "outlook.com": "Outlook",
  "samsung.com": "Samsung",
  "huawei.com": "Huawei",
  "dell.com": "Dell",
  "hp.com": "HP",
  "intel.com": "Intel",
  "amd.com": "AMD",
  "nvidia.com": "NVIDIA",
  "oracle.com": "Oracle",
  "sap.com": "SAP",
  "ibm.com": "IBM",
  "cisco.com": "Cisco",
  "shopify.com": "Shopify",
  "squarespace.com": "Squarespace",
  "godaddy.com": "GoDaddy",
  "bluehost.com": "Bluehost",
  "hostgator.com": "HostGator",
  "constantcontact.com": "Constant Contact",
  "mailchimp.com": "Mailchimp",
  "hubspot.com": "HubSpot",
  "stripe.com": "Stripe",
  "coinbase.com": "Coinbase",
  "binance.com": "Binance",
  "bitbucket.org": "Bitbucket",
  "sourceforge.net": "SourceForge",
  "unity.com": "Unity",
  "autodesk.com": "Autodesk",
  "behance.net": "Behance",
  "dribbble.com": "Dribbble",
  "deviantart.com": "DeviantArt",
  "flickr.com": "Flickr",
  "shutterstock.com": "Shutterstock",
  "istockphoto.com": "iStockphoto",
  "unsplash.com": "Unsplash",
  "pexels.com": "Pexels",
  "archive.org": "Internet Archive",
  "wikileaks.org": "WikiLeaks",
  "eff.org": "Electronic Frontier Foundation",
  "aclu.org": "American Civil Liberties Union",
  "redcross.org": "American Red Cross",
  "who.int": "World Health Organization",
  "un.org": "United Nations",
  "cia.gov": "CIA",
  "fbi.gov": "FBI",
  "nasa.gov": "NASA",
  "usps.com": "United States Postal Service",
  "fedex.com": "FedEx",
  "ups.com": "UPS",
  "delta.com": "Delta Air Lines",
  "united.com": "United Airlines",
  "southwest.com": "Southwest Airlines",
  "expedia.com": "Expedia",
  "hotels.com": "Hotels.com",
  "airbnb.com": "Airbnb",
  "zillow.com": "Zillow",
  "redfin.com": "Redfin",
  "cars.com": "Cars.com",
  "kbb.com": "Kelley Blue Book",
  "autotrader.com": "AutoTrader",
  "bestbuy.com": "Best Buy",
  "target.com": "Target",
  "homedepot.com": "Home Depot",
  "lowes.com": "Lowe's",
  "costco.com": "Costco",
  "macys.com": "Macy's",
  "sephora.com": "Sephora",
  "ulta.com": "Ulta Beauty",
  "nike.com": "Nike",
  "adidas.com": "Adidas",
  "puma.com": "Puma",
  "gap.com": "Gap",
  "hm.com": "H&M",
  "zara.com": "Zara",
  "asos.com": "ASOS",
  "shein.com": "Shein",
  "aliexpress.com": "AliExpress",
  "indiegogo.com": "Indiegogo",
  "kickstarter.com": "Kickstarter",
  "udemy.com": "Udemy",
  "coursera.org": "Coursera",
  "edx.org": "edX",
  "khanacademy.org": "Khan Academy",
  "duolingo.com": "Duolingo",
  "rottentomatoes.com": "Rotten Tomatoes",
  "imdb.com": "IMDb",
  "metacritic.com": "Metacritic",
  "goodreads.com": "Goodreads",
  "brainyquote.com": "BrainyQuote",
  "dictionary.com": "Dictionary.com",
  "merriam-webster.com": "Merriam-Webster",
  "thesaurus.com": "Thesaurus.com",
  "accuweather.com": "AccuWeather",
  "pixiv.net": "Pixiv",
  "nicovideo.jp": "Nico Nico Douga",
  "bilibili.com": "Bilibili",
  "line.me": "LINE",
  "kakao.com": "Kakao",
  "patreon.com": "Patreon",
  "telegram.me": "Telegram",
  "signal.org": "Signal",
  "wire.com": "Wire",
  "riotgames.com": "Riot Games",
  "blizzard.com": "Blizzard Entertainment",
  "ea.com": "Electronic Arts",
  "ubisoft.com": "Ubisoft",
  "rockstargames.com": "Rockstar Games",
  "bethesda.net": "Bethesda",
  "wiley.com": "Wiley",
  "elsevier.com": "Elsevier",
  "springer.com": "Springer",
  "mit.edu": "MIT",
  "harvard.edu": "Harvard University",
  "stanford.edu": "Stanford University",
  "ox.ac.uk": "University of Oxford",
  "cam.ac.uk": "University of Cambridge",
  "caltech.edu": "California Institute of Technology",
  "ucla.edu": "UCLA",
  "umich.edu": "University of Michigan",
  "ucsd.edu": "University of California, San Diego",
  "princeton.edu": "Princeton University",
  "yale.edu": "Yale University",
  "columbia.edu": "Columbia University",
  "penn.edu": "University of Pennsylvania",
  "duke.edu": "Duke University",
  "jhu.edu": "Johns Hopkins University",
  "mcgill.ca": "McGill University",
  "utoronto.ca": "University of Toronto",
  "ethz.ch": "ETH Zurich",
  "tsinghua.edu.cn": "Tsinghua University",
  "u-tokyo.ac.jp": "University of Tokyo",
  "kyoto-u.ac.jp": "Kyoto University",
  "anu.edu.au": "Australian National University",
  "imperial.ac.uk": "Imperial College London",
  "epfl.ch": "EPFL",
  "nus.edu.sg": "National University of Singapore",
  "ntu.edu.sg": "Nanyang Technological University",
  "bloombergquint.com": "BloombergQuint",
  "cnbc.com": "CNBC",
  "forbes.com": "Forbes",
  "fortune.com": "Fortune",
  "businessinsider.com": "Business Insider",
  "techcrunch.com": "TechCrunch",
  "wired.com": "Wired",
  "gizmodo.com": "Gizmodo",
  "theverge.com": "The Verge",
  "arstechnica.com": "Ars Technica",
  "mashable.com": "Mashable",
  "vice.com": "Vice",
  "nationalgeographic.com": "National Geographic",
  "discovery.com": "Discovery",
  "history.com": "History Channel",
  "natgeo.com": "National Geographic",
  "space.com": "Space.com",
  "newscientist.com": "New Scientist",
  "nature.com": "Nature",
  "sciencemag.org": "Science",
  "webmd.com": "WebMD",
  "mayoclinic.org": "Mayo Clinic",
  "healthline.com": "Healthline",
  "everydayhealth.com": "Everyday Health",
  "fda.gov": "FDA",
  "epa.gov": "EPA",
  "doi.gov": "Department of the Interior",
  "state.gov": "U.S. Department of State",
  "defense.gov": "U.S. Department of Defense",
  "treasury.gov": "U.S. Department of the Treasury",
  "justice.gov": "U.S. Department of Justice",
  "commerce.gov": "U.S. Department of Commerce",
  "energy.gov": "U.S. Department of Energy",
  "education.gov": "U.S. Department of Education",
  "transportation.gov": "U.S. Department of Transportation",
  "hud.gov": "U.S. Department of Housing and Urban Development",
  "agriculture.gov": "U.S. Department of Agriculture",
  "nfl.com": "NFL",
  "nba.com": "NBA",
  "mlb.com": "MLB",
  "nhl.com": "NHL",
  "fifa.com": "FIFA",
  "icc-cricket.com": "International Cricket Council",
  "formula1.com": "Formula 1",
  "usopen.org": "US Open",
  "wimbledon.com": "Wimbledon",
  "x.com": "X ( Twitter )",
  "baidu.com": "Baidu",
  "whatsapp.com": "WhatsApp",
  "tumblr.com": "Tumblr",
  "stackoverflow.com": "Stack Overflow",
  "openai.com": "OpenAI",
  "chase.com": "Chase Bank",
  "mantine.dev": "Mantine",
  "npmjs.com": "npm",
  "pypi.org": "PyPI",
  "crates.io": "crates.io",
  "docker.com": "Docker",
  "docker.io": "Docker",
  "apache.org": "Apache Software Foundation",
  "kernel.org": "Linux Kernel",
  "gnu.org": "GNU Project",
  "kubernetes.io": "Kubernetes",
  "djangoproject.com": "Django Project",
  "flask.palletsprojects.com": "Flask Project",
  "reactjs.org": "React",
  "vuejs.org": "Vue.js",
  "angular.io": "Angular",
  "tensorflow.org": "TensorFlow",
  "pytorch.org": "PyTorch",
  "opencv.org": "OpenCV",
  "electronjs.org": "Electron",
  "nodejs.org": "Node.js",
  "python.org": "Python",
  "ruby-lang.org": "Ruby",
  "rust-lang.org": "Rust",
  "golang.org": "Go",
  "llvm.org": "LLVM",
  "w3.org": "World Wide Web Consortium",
  "freebsd.org": "FreeBSD",
  "debian.org": "Debian",
  "ubuntu.com": "Ubuntu",
  "fedora.org": "Fedora",
  "archlinux.org": "Arch Linux",
  "opensuse.org": "openSUSE",
  "wordpress.org": "WordPress",
  "joomla.org": "Joomla!",
  "drupal.org": "Drupal",
  "mediawiki.org": "MediaWiki",
  "git-scm.com": "Git",
  "sqlite.org": "SQLite",
  "postgresql.org": "PostgreSQL",
  "mysql.com": "MySQL",
  "redis.io": "Redis",
  "mongodb.com": "MongoDB",
  "elastic.co": "Elasticsearch",
  "grafana.com": "Grafana",
  "prometheus.io": "Prometheus",
  "wireshark.org": "Wireshark",
  "vlc.org": "VLC media player",
  "blender.org": "Blender",
  "inkscape.org": "Inkscape",
  "gimp.org": "GIMP",
  "audacityteam.org": "Audacity",
  "libreelec.tv": "LibreELEC",
  "kodi.tv": "Kodi",
  "x.org": "X.Org Foundation",
  "freedesktop.org": "freedesktop.org",
  "gnome.org": "GNOME",
  "kde.org": "KDE",
  "xfce.org": "XFCE",
  "virtualbox.org": "VirtualBox",
  "qemu.org": "QEMU",
  "libvirt.org": "libvirt",
  "wixtoolset.org": "WiX Toolset",
  "cmake.org": "CMake",
  "boost.org": "Boost C++ Libraries",
  "qt.io": "Qt",
  "wxwidgets.org": "wxWidgets",
  "eclipse.org": "Eclipse Foundation",
  "netbeans.apache.org": "NetBeans",
  "intellij.com": "IntelliJ IDEA Community Edition",
  "code.visualstudio.com": "Visual Studio Code (OSS parts)",
  "v8.dev": "V8 JavaScript Engine",
  "chromium.org": "Chromium",
  "gcc.gnu.org": "GCC",
  "ffmpeg.org": "FFmpeg",
  "xiph.org": "Xiph.Org Foundation",
  "imagemagick.org": "ImageMagick",
  "pdftk.com": "PDFtk",
  "texlive.org": "TeX Live",
  "latex-project.org": "LaTeX Project",
  "zlib.net": "zlib",
  "openssl.org": "OpenSSL",
  "libpng.org": "libpng",
  "jpeg.org": "Independent JPEG Group",
  "libtiff.org": "libtiff",
  "expat.sourceforge.net": "Expat",
  "libxml.org": "libxml2",
  "libxslt.org": "libxslt",
  "curl.se": "curl",
  "wget.org": "GNU Wget",
  "tcpdump.org": "tcpdump",
  "nmap.org": "Nmap",
  "git-for-windows.github.io": "Git for Windows",
  "msys2.org": "MSYS2",
  "cygwin.com": "Cygwin",
  "mingw-w64.org": "MinGW-w64",
  "reactnative.dev": "React Native",
  "flutter.dev": "Flutter",
  "dart.dev": "Dart",
  "kotlinlang.org": "Kotlin",
  "swift.org": "Swift",
  "haskell.org": "Haskell",
  "erlang.org": "Erlang",
  "elixir-lang.org": "Elixir",
  "clojure.org": "Clojure",
  "scala-lang.org": "Scala",
  "perl.org": "Perl",
  "php.net": "PHP",
  "r-project.org": "R Project",
  "julia-lang.org": "Julia",
  "lua.org": "Lua",
  "ziglang.org": "Zig",
  "nim-lang.org": "Nim",
  "crystal-lang.org": "Crystal",
  "dlang.org": "D",
  "ada-lang.io": "Ada",
  "fortran-lang.org": "Fortran",
  "ocaml.org": "OCaml",
  "haxe.org": "Haxe",
  "reasonml.github.io": "ReasonML",
  "elm-lang.org": "Elm",
  "purescript.org": "PureScript",
  "fsharp.org": "F#",
  "google.co.uk": "Google UK",
  "google.de": "Google Germany",
  "google.fr": "Google France",
  "google.es": "Google Spain",
  "google.it": "Google Italy",
  "google.co.jp": "Google Japan",
  "google.ru": "Google Russia",
  "google.com.br": "Google Brazil",
  "google.ca": "Google Canada",
  "google.com.au": "Google Australia",
  "google.co.in": "Google India",
  "dailymotion.com": "Dailymotion",
  "wikimedia.org": "Wikimedia",
  "openstreetmap.org": "OpenStreetMap",
  "pixabay.com": "Pixabay",
};
