export const COOL_WEBSITES = [
  // Cool websites
  "https://radio.garden",
  "https://www.futureme.org",
  "https://pointerpointer.com",
  "https://www.window-swap.com",
  "https://joshworth.com/dev/pixelspace/pixelspace_solarsystem.html",
  "https://www.cameronsworld.net",
  "https://www.blitzortung.org/en/live_lightning_maps.php",
  "https://neal.fun",
  "https://upalc.com/follow-the-mouse.php",
  "https://ncase.me",
  "https://sandspiel.club",
  "https://www.kfchess.com",
  "https://www.myretrotvs.com",
  "https://www.windows93.net",
  "https://www.howmanypeopleareinspacerightnow.com",
  "https://thetruesize.com",
  "https://krunker.io",
  "https://www.citywalki.com",
  "https://ismy.blue",
  "https://368chickens.com",
  "https://chaz.fun/phone/3250",
  "https://www.lingscars.com",
];
